//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCompleteApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:50358/AutoGetTime.asmx")]
        public string AutoCompleteApp_AutoService_AutoGetTime {
            get {
                return ((string)(this["AutoCompleteApp_AutoService_AutoGetTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://autocomplete.omsttech.com/AutoGetTime.asmx")]
        public string AutoCompleteApp_AutoServiceLive_AutoGetTime {
            get {
                return ((string)(this["AutoCompleteApp_AutoServiceLive_AutoGetTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51416/WebService/AutoCompleteOMST.asmx")]
        public string AutoCompleteApp_LiveWebLocalHost_AutoCompleteOMST {
            get {
                return ((string)(this["AutoCompleteApp_LiveWebLocalHost_AutoCompleteOMST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://autocompleteadmin.omsttech.com/WebService/AutoCompleteOMST.asmx")]
        public string AutoCompleteApp_autocompleteadminLive_AutoCompleteOMST {
            get {
                return ((string)(this["AutoCompleteApp_autocompleteadminLive_AutoCompleteOMST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://autocomplete.azurewebsites.net/WebService/AutoCompleteOMST.asmx")]
        public string AutoCompleteApp_net_azurewebsites_autocomplete_AutoCompleteOMST {
            get {
                return ((string)(this["AutoCompleteApp_net_azurewebsites_autocomplete_AutoCompleteOMST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.totalautocomplete.com/WebService/AutoCompleteOMST.asmx")]
        public string AutoCompleteApp_totalautocompleteLive_AutoCompleteOMST {
            get {
                return ((string)(this["AutoCompleteApp_totalautocompleteLive_AutoCompleteOMST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://autocompleteadmin.omsttech.com/WebService/YoutubeService.asmx")]
        public string AutoCompleteApp_YoutubeService_YoutubeService {
            get {
                return ((string)(this["AutoCompleteApp_YoutubeService_YoutubeService"]));
            }
        }
    }
}
