//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AutoCompleteApp.YoutubeService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="YoutubeServiceSoap", Namespace="http://tempuri.org/")]
    public partial class YoutubeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SelectTopKeywordYoutubeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetSearchCounterYoutubeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetSearchCounterForHoldKeywordsYoutubeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectTopProxyOperationCompleted;
        
        private System.Threading.SendOrPostCallback LockDownKeywordYoutubeOperationCompleted;
        
        private System.Threading.SendOrPostCallback LockDownProxyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReleaseKeywordYoutubeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReleaseProxyOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncreaseSearchCounterYoutubeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public YoutubeService() {
            this.Url = global::AutoCompleteApp.Properties.Settings.Default.AutoCompleteApp_YoutubeService_YoutubeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SelectTopKeywordYoutubeCompletedEventHandler SelectTopKeywordYoutubeCompleted;
        
        /// <remarks/>
        public event ResetSearchCounterYoutubeCompletedEventHandler ResetSearchCounterYoutubeCompleted;
        
        /// <remarks/>
        public event ResetSearchCounterForHoldKeywordsYoutubeCompletedEventHandler ResetSearchCounterForHoldKeywordsYoutubeCompleted;
        
        /// <remarks/>
        public event SelectTopProxyCompletedEventHandler SelectTopProxyCompleted;
        
        /// <remarks/>
        public event LockDownKeywordYoutubeCompletedEventHandler LockDownKeywordYoutubeCompleted;
        
        /// <remarks/>
        public event LockDownProxyCompletedEventHandler LockDownProxyCompleted;
        
        /// <remarks/>
        public event ReleaseKeywordYoutubeCompletedEventHandler ReleaseKeywordYoutubeCompleted;
        
        /// <remarks/>
        public event ReleaseProxyCompletedEventHandler ReleaseProxyCompleted;
        
        /// <remarks/>
        public event IncreaseSearchCounterYoutubeCompletedEventHandler IncreaseSearchCounterYoutubeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectTopKeywordYoutube", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SelectTopKeywordYoutube(int Id, bool IsTesting) {
            object[] results = this.Invoke("SelectTopKeywordYoutube", new object[] {
                        Id,
                        IsTesting});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SelectTopKeywordYoutubeAsync(int Id, bool IsTesting) {
            this.SelectTopKeywordYoutubeAsync(Id, IsTesting, null);
        }
        
        /// <remarks/>
        public void SelectTopKeywordYoutubeAsync(int Id, bool IsTesting, object userState) {
            if ((this.SelectTopKeywordYoutubeOperationCompleted == null)) {
                this.SelectTopKeywordYoutubeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectTopKeywordYoutubeOperationCompleted);
            }
            this.InvokeAsync("SelectTopKeywordYoutube", new object[] {
                        Id,
                        IsTesting}, this.SelectTopKeywordYoutubeOperationCompleted, userState);
        }
        
        private void OnSelectTopKeywordYoutubeOperationCompleted(object arg) {
            if ((this.SelectTopKeywordYoutubeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectTopKeywordYoutubeCompleted(this, new SelectTopKeywordYoutubeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetSearchCounterYoutube", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ResetSearchCounterYoutube(bool IsTesting) {
            object[] results = this.Invoke("ResetSearchCounterYoutube", new object[] {
                        IsTesting});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ResetSearchCounterYoutubeAsync(bool IsTesting) {
            this.ResetSearchCounterYoutubeAsync(IsTesting, null);
        }
        
        /// <remarks/>
        public void ResetSearchCounterYoutubeAsync(bool IsTesting, object userState) {
            if ((this.ResetSearchCounterYoutubeOperationCompleted == null)) {
                this.ResetSearchCounterYoutubeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetSearchCounterYoutubeOperationCompleted);
            }
            this.InvokeAsync("ResetSearchCounterYoutube", new object[] {
                        IsTesting}, this.ResetSearchCounterYoutubeOperationCompleted, userState);
        }
        
        private void OnResetSearchCounterYoutubeOperationCompleted(object arg) {
            if ((this.ResetSearchCounterYoutubeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetSearchCounterYoutubeCompleted(this, new ResetSearchCounterYoutubeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetSearchCounterForHoldKeywordsYoutube", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ResetSearchCounterForHoldKeywordsYoutube(bool IsTesting) {
            object[] results = this.Invoke("ResetSearchCounterForHoldKeywordsYoutube", new object[] {
                        IsTesting});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ResetSearchCounterForHoldKeywordsYoutubeAsync(bool IsTesting) {
            this.ResetSearchCounterForHoldKeywordsYoutubeAsync(IsTesting, null);
        }
        
        /// <remarks/>
        public void ResetSearchCounterForHoldKeywordsYoutubeAsync(bool IsTesting, object userState) {
            if ((this.ResetSearchCounterForHoldKeywordsYoutubeOperationCompleted == null)) {
                this.ResetSearchCounterForHoldKeywordsYoutubeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetSearchCounterForHoldKeywordsYoutubeOperationCompleted);
            }
            this.InvokeAsync("ResetSearchCounterForHoldKeywordsYoutube", new object[] {
                        IsTesting}, this.ResetSearchCounterForHoldKeywordsYoutubeOperationCompleted, userState);
        }
        
        private void OnResetSearchCounterForHoldKeywordsYoutubeOperationCompleted(object arg) {
            if ((this.ResetSearchCounterForHoldKeywordsYoutubeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetSearchCounterForHoldKeywordsYoutubeCompleted(this, new ResetSearchCounterForHoldKeywordsYoutubeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectTopProxy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SelectTopProxy(int Id) {
            object[] results = this.Invoke("SelectTopProxy", new object[] {
                        Id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SelectTopProxyAsync(int Id) {
            this.SelectTopProxyAsync(Id, null);
        }
        
        /// <remarks/>
        public void SelectTopProxyAsync(int Id, object userState) {
            if ((this.SelectTopProxyOperationCompleted == null)) {
                this.SelectTopProxyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectTopProxyOperationCompleted);
            }
            this.InvokeAsync("SelectTopProxy", new object[] {
                        Id}, this.SelectTopProxyOperationCompleted, userState);
        }
        
        private void OnSelectTopProxyOperationCompleted(object arg) {
            if ((this.SelectTopProxyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectTopProxyCompleted(this, new SelectTopProxyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LockDownKeywordYoutube", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LockDownKeywordYoutube(int Id) {
            this.Invoke("LockDownKeywordYoutube", new object[] {
                        Id});
        }
        
        /// <remarks/>
        public void LockDownKeywordYoutubeAsync(int Id) {
            this.LockDownKeywordYoutubeAsync(Id, null);
        }
        
        /// <remarks/>
        public void LockDownKeywordYoutubeAsync(int Id, object userState) {
            if ((this.LockDownKeywordYoutubeOperationCompleted == null)) {
                this.LockDownKeywordYoutubeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLockDownKeywordYoutubeOperationCompleted);
            }
            this.InvokeAsync("LockDownKeywordYoutube", new object[] {
                        Id}, this.LockDownKeywordYoutubeOperationCompleted, userState);
        }
        
        private void OnLockDownKeywordYoutubeOperationCompleted(object arg) {
            if ((this.LockDownKeywordYoutubeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LockDownKeywordYoutubeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LockDownProxy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LockDownProxy(int Id) {
            this.Invoke("LockDownProxy", new object[] {
                        Id});
        }
        
        /// <remarks/>
        public void LockDownProxyAsync(int Id) {
            this.LockDownProxyAsync(Id, null);
        }
        
        /// <remarks/>
        public void LockDownProxyAsync(int Id, object userState) {
            if ((this.LockDownProxyOperationCompleted == null)) {
                this.LockDownProxyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLockDownProxyOperationCompleted);
            }
            this.InvokeAsync("LockDownProxy", new object[] {
                        Id}, this.LockDownProxyOperationCompleted, userState);
        }
        
        private void OnLockDownProxyOperationCompleted(object arg) {
            if ((this.LockDownProxyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LockDownProxyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReleaseKeywordYoutube", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReleaseKeywordYoutube(int Id) {
            this.Invoke("ReleaseKeywordYoutube", new object[] {
                        Id});
        }
        
        /// <remarks/>
        public void ReleaseKeywordYoutubeAsync(int Id) {
            this.ReleaseKeywordYoutubeAsync(Id, null);
        }
        
        /// <remarks/>
        public void ReleaseKeywordYoutubeAsync(int Id, object userState) {
            if ((this.ReleaseKeywordYoutubeOperationCompleted == null)) {
                this.ReleaseKeywordYoutubeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReleaseKeywordYoutubeOperationCompleted);
            }
            this.InvokeAsync("ReleaseKeywordYoutube", new object[] {
                        Id}, this.ReleaseKeywordYoutubeOperationCompleted, userState);
        }
        
        private void OnReleaseKeywordYoutubeOperationCompleted(object arg) {
            if ((this.ReleaseKeywordYoutubeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReleaseKeywordYoutubeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReleaseProxy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReleaseProxy(int Id) {
            this.Invoke("ReleaseProxy", new object[] {
                        Id});
        }
        
        /// <remarks/>
        public void ReleaseProxyAsync(int Id) {
            this.ReleaseProxyAsync(Id, null);
        }
        
        /// <remarks/>
        public void ReleaseProxyAsync(int Id, object userState) {
            if ((this.ReleaseProxyOperationCompleted == null)) {
                this.ReleaseProxyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReleaseProxyOperationCompleted);
            }
            this.InvokeAsync("ReleaseProxy", new object[] {
                        Id}, this.ReleaseProxyOperationCompleted, userState);
        }
        
        private void OnReleaseProxyOperationCompleted(object arg) {
            if ((this.ReleaseProxyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReleaseProxyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncreaseSearchCounterYoutube", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IncreaseSearchCounterYoutube(int Id) {
            this.Invoke("IncreaseSearchCounterYoutube", new object[] {
                        Id});
        }
        
        /// <remarks/>
        public void IncreaseSearchCounterYoutubeAsync(int Id) {
            this.IncreaseSearchCounterYoutubeAsync(Id, null);
        }
        
        /// <remarks/>
        public void IncreaseSearchCounterYoutubeAsync(int Id, object userState) {
            if ((this.IncreaseSearchCounterYoutubeOperationCompleted == null)) {
                this.IncreaseSearchCounterYoutubeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncreaseSearchCounterYoutubeOperationCompleted);
            }
            this.InvokeAsync("IncreaseSearchCounterYoutube", new object[] {
                        Id}, this.IncreaseSearchCounterYoutubeOperationCompleted, userState);
        }
        
        private void OnIncreaseSearchCounterYoutubeOperationCompleted(object arg) {
            if ((this.IncreaseSearchCounterYoutubeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncreaseSearchCounterYoutubeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SelectTopKeywordYoutubeCompletedEventHandler(object sender, SelectTopKeywordYoutubeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectTopKeywordYoutubeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectTopKeywordYoutubeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ResetSearchCounterYoutubeCompletedEventHandler(object sender, ResetSearchCounterYoutubeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetSearchCounterYoutubeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetSearchCounterYoutubeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ResetSearchCounterForHoldKeywordsYoutubeCompletedEventHandler(object sender, ResetSearchCounterForHoldKeywordsYoutubeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetSearchCounterForHoldKeywordsYoutubeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetSearchCounterForHoldKeywordsYoutubeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SelectTopProxyCompletedEventHandler(object sender, SelectTopProxyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectTopProxyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectTopProxyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LockDownKeywordYoutubeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LockDownProxyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReleaseKeywordYoutubeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReleaseProxyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void IncreaseSearchCounterYoutubeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591